"""离子和中性分子的物理参数（兼容层，定义见 FieldConfiguration.ion_species）。"""
from FieldConfiguration.ion_species import (  # noqa: F401
    AMU,
    BA_135,
    BA_138,
    BE_9,
    CA_40,
    EC,
    EPS0,
    HE_MOLECULE,
    H2_MOLECULE,
    ION_SPECIES,
    KB,
    MG_24,
    MOL_SPECIES,
    SR_88,
    Species,
    YB_171,
    polarization_coefficient,
    reduced_mass,
)

__all__ = [
    "AMU",
    "EPS0",
    "EC",
    "KB",
    "Species",
    "H2_MOLECULE",
    "HE_MOLECULE",
    "BA_135",
    "BA_138",
    "YB_171",
    "CA_40",
    "SR_88",
    "MG_24",
    "BE_9",
    "ION_SPECIES",
    "MOL_SPECIES",
    "reduced_mass",
    "polarization_coefficient",
]
